services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_USER}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 3

  user-service:
    build: ./userService
    ports:
      - "8001:8001"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - MONGO_URI=mongodb+srv://karthikrajcode:neverSettle20@microservices.72r7cq6.mongodb.net/routinesApp?retryWrites=true&w=majority
      - JWT_SECRET=routine_secret
    depends_on:
      rabbitmq:
        condition: service_healthy

  routine-service:
    build: ./routineService
    ports:
      - "8002:8002"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb+srv://karthikrajcode:neverSettle20@microservices.72r7cq6.mongodb.net/routinesApp?retryWrites=true&w=majority
      - JWT_SECRET=routine_secret
    depends_on:
      rabbitmq:
        condition: service_healthy

  rl-service:
    build: ./rl_service
    ports:
      - "8003:8003"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

      - REDIS_URL=redis://redis:6379
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - ROUTINE_SERVICE_URL=http://routine-service:8002
      - USER_SERVICE_URL=https://rl-service-uldq.onrender.com
      - RL_SERVICE_URL=http://rl-service:8003
    depends_on:
      - user-service
      - routine-service
      - rl-service



  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
