services:
  # User Service
  - name: user-service
    type: web
    runtime: docker
    repo: https://github.com/KarthikrajS/routine-api.git
    dockerfilePath: ./userService/Dockerfile
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: RABBITMQ_URL
        value: amqp://guest:guest@rabbitmq:5672
      - key: MONGO_URI
        value: mongodb+srv://karthikrajcode:neverSettle20@microservices.72r7cq6.mongodb.net/routinesApp?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: routine_secret

  # Routine Service
  - name: routine-service
    type: web
    runtime: docker
    repo: https://github.com/KarthikrajS/routine-api.git
    dockerfilePath: ./routineService/Dockerfile
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: RABBITMQ_URL
        value: amqp://guest:guest@rabbitmq:5672
      - key: REDIS_URL
        value: redis://redis:6379
      - key: MONGO_URI
        value: mongodb+srv://karthikrajcode:neverSettle20@microservices.72r7cq6.mongodb.net/routinesApp?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: routine_secret

  # RL Service
  - name: rl-service
    type: web
    runtime: docker
    repo: https://github.com/KarthikrajS/routine-api.git
    dockerfilePath: ./rl_service/Dockerfile
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: RABBITMQ_URL
        value: amqp://guest:guest@rabbitmq:5672
      - key: REDIS_URL
        value: redis://redis:6379

  # Gateway Service
  - name: gateway
    type: web
    runtime: docker
    repo: https://github.com/KarthikrajS/routine-api.git
    dockerfilePath: ./gateway/Dockerfile
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: ROUTINE_SERVICE_URL
        value: http://routine-service:8002
      - key: USER_SERVICE_URL
        value: http://user-service:8001
      - key: RL_SERVICE_URL
        value: http://rl-service:8003

  # RabbitMQ Service
  - name: rabbitmq
    type: pserv
    runtime: docker
    repo: https://github.com/KarthikrajS/routine-api.git
    dockerCommand: rabbitmq:management
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: guest
      - key: RABBITMQ_DEFAULT_PASS
        value: guest
    plan: free

  # Redis Service
  - name: redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all
